import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './Components/Header'
import  Footer  from './Components/Footer'
import {MantineProvider} from '@mantine/core'
import {Theme} from './Theme/Theme'
// import '@mantine/core/dist/styles.css';
import { Rubik } from 'next/font/google'


const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css"/>

      </head>
      <body className={rubik.className} >
      <MantineProvider  >
        <Header/>
        
          {children}
        <Footer/>
      </MantineProvider> 
      </body>
    </html>
  )
}
